<?php

namespace app\modules\admin\controllers;

use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class DefaultController extends Controller
{
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['logout', 'login'],
				'denyCallback' => function ($rule, $action) {
					throw new \Exception('You are not allowed to access this page');
				},
				'rules' => [
					[
						'allow' => false,
						'actions' => ['login', 'signup'],
						'roles' => ['?'],
					],
					[
						'actions' => ['logout'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}

	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class' => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}
	
	public function beforeAction($action)
	{
		Yii::$app->session->open();
		if (\Yii::$app->user->isGuest) {
			return Yii::$app->getResponse()->redirect(Yii::$app->user->loginUrl[0]);
		}

		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}

	public function actionIndex()
	{
		return $this->render('index');
	}
	
}