<?php

namespace app\modules\admin\base;

use yii;
use yii\web\Controller;

class BaseController extends Controller
{

	public function beforeAction($action)
	{
//		return Yii::$app->getResponse()->redirect('default/login');
//		die('<pre>' . print_r($action,1) . '</pre>');
		if (\Yii::$app->user->isGuest && Yii::$app->controller->action->id != 'login' ) {
			//return Yii::$app->getResponse()->redirect(Yii::$app->getUser()->loginUrl);
			return Yii::$app->getResponse()->redirect('/admin/default/login');
		}
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}

}
